services:
  - type: web
    name: polychat
    env: node
    plan: free
    buildCommand: cd web && npm ci --legacy-peer-deps && npm run build
    startCommand: cd web && npm start
    envVars:
      - key: NODE_ENV
        value: production
