services:
  - type: web
    name: polychat
    env: node
    plan: free
    root: web
    build:
      command: cd web && npm ci && npm run build
    start: npm start
    envVars:
      - key: NODE_ENV
        value: production
